default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: gentle-bronto-redesign_development
test:
  <<: *default
  database: gentle-bronto-redesign_test
production:
  <<: *default
  database: gentle-bronto-redesign_production
  username: gentle-bronto-redesign
  password: <%= ENV['GENTLE-BRONTO-REDESIGN_DATABASE_PASSWORD'] %>
